//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChristmasTree {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChristmasTree.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxHeaderError {
            get {
                return ResourceManager.GetString("MessageBoxHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MessageBoxHeaderInfo {
            get {
                return ResourceManager.GetString("MessageBoxHeaderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image saved successfully..
        /// </summary>
        public static string MessageBoxMessageImageSavedInfo {
            get {
                return ResourceManager.GetString("MessageBoxMessageImageSavedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save image:.
        /// </summary>
        public static string MessageBoxMessageImageSaveError {
            get {
                return ResourceManager.GetString("MessageBoxMessageImageSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The save function is available in the full version only. Do you want to purchase full version now?.
        /// </summary>
        public static string MessageBoxMessageImageSaveTrialVersionQuestion {
            get {
                return ResourceManager.GetString("MessageBoxMessageImageSaveTrialVersionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open Marketplace:.
        /// </summary>
        public static string MessageBoxMessageMarketplaceOpenError {
            get {
                return ResourceManager.GetString("MessageBoxMessageMarketplaceOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings are available in the full version only. Do you want to purchase full version now?.
        /// </summary>
        public static string MessageBoxMessageSettingsTrialVersionQuestion {
            get {
                return ResourceManager.GetString("MessageBoxMessageSettingsTrialVersionQuestion", resourceCulture);
            }
        }
    }
}
